/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125GuestRouteImport } from './routes/{-$locale}/_guest'
import { Route as Char123LocaleChar125AuthenticatedRouteImport } from './routes/{-$locale}/_authenticated'
import { Route as Char123LocaleChar125GuestSignUpRouteRouteImport } from './routes/{-$locale}/_guest/sign-up/route'
import { Route as Char123LocaleChar125GuestSignInRouteRouteImport } from './routes/{-$locale}/_guest/sign-in/route'
import { Route as Char123LocaleChar125AuthenticatedDashboardRouteRouteImport } from './routes/{-$locale}/_authenticated/dashboard/route'
import { Route as Char123LocaleChar125AuthenticatedContactsRouteRouteImport } from './routes/{-$locale}/_authenticated/contacts/route'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125GuestRoute =
  Char123LocaleChar125GuestRouteImport.update({
    id: '/_guest',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthenticatedRoute =
  Char123LocaleChar125AuthenticatedRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125GuestSignUpRouteRoute =
  Char123LocaleChar125GuestSignUpRouteRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => Char123LocaleChar125GuestRoute,
  } as any)
const Char123LocaleChar125GuestSignInRouteRoute =
  Char123LocaleChar125GuestSignInRouteRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => Char123LocaleChar125GuestRoute,
  } as any)
const Char123LocaleChar125AuthenticatedDashboardRouteRoute =
  Char123LocaleChar125AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)
const Char123LocaleChar125AuthenticatedContactsRouteRoute =
  Char123LocaleChar125AuthenticatedContactsRouteRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125GuestRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/contacts': typeof Char123LocaleChar125AuthenticatedContactsRouteRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125AuthenticatedDashboardRouteRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125GuestSignInRouteRoute
  '/{-$locale}/sign-up': typeof Char123LocaleChar125GuestSignUpRouteRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/contacts': typeof Char123LocaleChar125AuthenticatedContactsRouteRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125AuthenticatedDashboardRouteRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125GuestSignInRouteRoute
  '/{-$locale}/sign-up': typeof Char123LocaleChar125GuestSignUpRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/_authenticated': typeof Char123LocaleChar125AuthenticatedRouteWithChildren
  '/{-$locale}/_guest': typeof Char123LocaleChar125GuestRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/_authenticated/contacts': typeof Char123LocaleChar125AuthenticatedContactsRouteRoute
  '/{-$locale}/_authenticated/dashboard': typeof Char123LocaleChar125AuthenticatedDashboardRouteRoute
  '/{-$locale}/_guest/sign-in': typeof Char123LocaleChar125GuestSignInRouteRoute
  '/{-$locale}/_guest/sign-up': typeof Char123LocaleChar125GuestSignUpRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/contacts'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/{-$locale}/contacts'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/sign-up'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/_authenticated'
    | '/{-$locale}/_guest'
    | '/{-$locale}/'
    | '/{-$locale}/_authenticated/contacts'
    | '/{-$locale}/_authenticated/dashboard'
    | '/{-$locale}/_guest/sign-in'
    | '/{-$locale}/_guest/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_guest': {
      id: '/{-$locale}/_guest'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125GuestRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_authenticated': {
      id: '/{-$locale}/_authenticated'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_guest/sign-up': {
      id: '/{-$locale}/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/{-$locale}/sign-up'
      preLoaderRoute: typeof Char123LocaleChar125GuestSignUpRouteRouteImport
      parentRoute: typeof Char123LocaleChar125GuestRoute
    }
    '/{-$locale}/_guest/sign-in': {
      id: '/{-$locale}/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/{-$locale}/sign-in'
      preLoaderRoute: typeof Char123LocaleChar125GuestSignInRouteRouteImport
      parentRoute: typeof Char123LocaleChar125GuestRoute
    }
    '/{-$locale}/_authenticated/dashboard': {
      id: '/{-$locale}/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
    '/{-$locale}/_authenticated/contacts': {
      id: '/{-$locale}/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/{-$locale}/contacts'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedContactsRouteRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRoute
    }
  }
}

interface Char123LocaleChar125AuthenticatedRouteChildren {
  Char123LocaleChar125AuthenticatedContactsRouteRoute: typeof Char123LocaleChar125AuthenticatedContactsRouteRoute
  Char123LocaleChar125AuthenticatedDashboardRouteRoute: typeof Char123LocaleChar125AuthenticatedDashboardRouteRoute
}

const Char123LocaleChar125AuthenticatedRouteChildren: Char123LocaleChar125AuthenticatedRouteChildren =
  {
    Char123LocaleChar125AuthenticatedContactsRouteRoute:
      Char123LocaleChar125AuthenticatedContactsRouteRoute,
    Char123LocaleChar125AuthenticatedDashboardRouteRoute:
      Char123LocaleChar125AuthenticatedDashboardRouteRoute,
  }

const Char123LocaleChar125AuthenticatedRouteWithChildren =
  Char123LocaleChar125AuthenticatedRoute._addFileChildren(
    Char123LocaleChar125AuthenticatedRouteChildren,
  )

interface Char123LocaleChar125GuestRouteChildren {
  Char123LocaleChar125GuestSignInRouteRoute: typeof Char123LocaleChar125GuestSignInRouteRoute
  Char123LocaleChar125GuestSignUpRouteRoute: typeof Char123LocaleChar125GuestSignUpRouteRoute
}

const Char123LocaleChar125GuestRouteChildren: Char123LocaleChar125GuestRouteChildren =
  {
    Char123LocaleChar125GuestSignInRouteRoute:
      Char123LocaleChar125GuestSignInRouteRoute,
    Char123LocaleChar125GuestSignUpRouteRoute:
      Char123LocaleChar125GuestSignUpRouteRoute,
  }

const Char123LocaleChar125GuestRouteWithChildren =
  Char123LocaleChar125GuestRoute._addFileChildren(
    Char123LocaleChar125GuestRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AuthenticatedRoute: typeof Char123LocaleChar125AuthenticatedRouteWithChildren
  Char123LocaleChar125GuestRoute: typeof Char123LocaleChar125GuestRouteWithChildren
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AuthenticatedRoute:
      Char123LocaleChar125AuthenticatedRouteWithChildren,
    Char123LocaleChar125GuestRoute: Char123LocaleChar125GuestRouteWithChildren,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
